"""Gate `lockfile-sync`: o pin do lock precisa satisfazer o especificador do `.in`.

O incidente que motiva: até 2026-10-09 o gate só conferia PRESENÇA. PRs do
Dependabot subiam o piso no `.in` sem regenerar o lock, e em 2026-10-08 a `main`
violava 5 pisos já mergeados (sqlalchemy, pydantic-settings, litellm, otel-api,
otel-instrumentation-celery) com o hook verde — corrigido no #2046."""

from __future__ import annotations

from pathlib import Path

import pytest

from dev import check_lockfile_sync as mod

LOCK_HEADER = (
    "#\n"
    "# This file is autogenerated by pip-compile with Python 3.12\n"
    "# by the following command:\n"
    "#\n"
    "#    pip-compile --generate-hashes --output-file=requirements.lock"
    " --strip-extras backend/requirements.in requirements.in\n"
    "#\n"
)


def _lock(*pins: str) -> str:
    body = "".join(f"{pin} \\\n    --hash=sha256:{'0' * 64}\n    # via -r x.in\n" for pin in pins)
    return LOCK_HEADER + body


def _violations(tmp_path: Path, in_text: str, lock_text: str) -> list[str]:
    in_file = tmp_path / "requirements.in"
    lock_file = tmp_path / "requirements.lock"
    in_file.write_text(in_text, encoding="utf-8")
    lock_file.write_text(lock_text, encoding="utf-8")
    return mod.lockfile_violations((in_file,), lock_file, tmp_path)


def test_floor_above_lock_fails(tmp_path: Path) -> None:
    found = _violations(tmp_path, "sqlalchemy[asyncio]>=2.0.52\n", _lock("sqlalchemy==2.0.50"))
    assert found == ["requirements.in:1  sqlalchemy[asyncio]>=2.0.52  → lock pina 2.0.50"]


def test_lock_within_floor_passes(tmp_path: Path) -> None:
    assert _violations(tmp_path, "sqlalchemy[asyncio]>=2.0.52\n", _lock("sqlalchemy==2.0.54")) == []


def test_floor_equal_to_lock_passes(tmp_path: Path) -> None:
    assert _violations(tmp_path, "litellm>=1.97.0\n", _lock("litellm==1.97.0")) == []


def test_ceiling_below_lock_fails(tmp_path: Path) -> None:
    found = _violations(tmp_path, "numpy>=1.26,<3\n", _lock("numpy==3.0.1"))
    assert found == ["requirements.in:1  numpy>=1.26,<3  → lock pina 3.0.1"]


def test_missing_package_still_fails(tmp_path: Path) -> None:
    found = _violations(tmp_path, "fastapi>=0.115\n", _lock("starlette==0.48.0"))
    assert found == ["requirements.in:1  fastapi>=0.115  → ausente do lock"]


def test_prerelease_pin_inside_prerelease_floor_passes(tmp_path: Path) -> None:
    in_text = "opentelemetry-instrumentation-fastapi>=0.50b0\n"
    assert (
        _violations(tmp_path, in_text, _lock("opentelemetry-instrumentation-fastapi==0.65b0")) == []
    )


def test_prerelease_pin_below_prerelease_floor_fails(tmp_path: Path) -> None:
    in_text = "opentelemetry-instrumentation-celery>=0.65b0\n"
    found = _violations(tmp_path, in_text, _lock("opentelemetry-instrumentation-celery==0.63b1"))
    assert found == [
        "requirements.in:1  opentelemetry-instrumentation-celery>=0.65b0  → lock pina 0.63b1"
    ]


@pytest.mark.parametrize(
    ("declared", "pin"),
    [
        ("PyYAML>=6.0", "pyyaml==6.0.3"),
        ("eval_type_backport>=0.2.0", "eval-type-backport==0.3.1"),
        ("Zope.Interface>=6", "zope-interface==7.2"),
        ("celery[redis]>=5.6.3", "celery==5.6.3"),
        ("uvicorn[standard]>=0.30", "uvicorn==0.48.0"),
    ],
)
def test_pep503_names_and_extras_match_the_lock(tmp_path: Path, declared: str, pin: str) -> None:
    assert _violations(tmp_path, f"{declared}\n", _lock(pin)) == []


def test_marker_false_for_lock_target_is_not_required(tmp_path: Path) -> None:
    in_text = "tomli>=2.0; python_version < '3.11'\npywin32>=306; sys_platform == 'win32'\n"
    assert _violations(tmp_path, in_text, _lock("pyyaml==6.0.3")) == []


def test_marker_true_for_lock_target_is_checked(tmp_path: Path) -> None:
    in_text = "uvloop>=0.21; sys_platform == 'linux'\n"
    found = _violations(tmp_path, in_text, _lock("uvloop==0.19.0"))
    assert found == ["requirements.in:1  uvloop>=0.21; sys_platform == 'linux'  → lock pina 0.19.0"]


def test_comments_options_and_blank_lines_are_skipped(tmp_path: Path) -> None:
    in_text = (
        "# cabeçalho\n"
        "\n"
        "--index-url https://example.invalid/simple\n"
        "cryptography>=50.0.0  # SEC-03: comentário inline com >= e [x]\n"
    )
    assert _violations(tmp_path, in_text, _lock("cryptography==50.0.0")) == []


def test_same_package_in_two_in_files_is_checked_per_line(tmp_path: Path) -> None:
    (tmp_path / "backend").mkdir()
    root_in, backend_in = tmp_path / "requirements.in", tmp_path / "backend" / "requirements.in"
    lock_file = tmp_path / "requirements.lock"
    root_in.write_text("pdfplumber>=0.10\n", encoding="utf-8")
    backend_in.write_text("# web\npdfplumber>=0.12.0\n", encoding="utf-8")
    lock_file.write_text(_lock("pdfplumber==0.11.9"), encoding="utf-8")
    found = mod.lockfile_violations((root_in, backend_in), lock_file, tmp_path)
    assert found == ["backend/requirements.in:2  pdfplumber>=0.12.0  → lock pina 0.11.9"]


def test_the_five_floors_of_2026_10_08_all_fail(tmp_path: Path) -> None:
    """Contrafactual do incidente: o gate de presença deixava passar os 5."""
    in_text = (
        "sqlalchemy[asyncio]>=2.0.52\n"
        "pydantic-settings>=2.15.0\n"
        "litellm>=1.97.0\n"
        "opentelemetry-api>=1.44.0\n"
        "opentelemetry-instrumentation-celery>=0.65b0\n"
    )
    lock_text = _lock(
        "sqlalchemy==2.0.50",
        "pydantic-settings==2.14.2",
        "litellm==1.86.2",
        "opentelemetry-api==1.42.1",
        "opentelemetry-instrumentation-celery==0.63b1",
    )
    assert len(_violations(tmp_path, in_text, lock_text)) == 5


def test_unparseable_line_fails_loud(tmp_path: Path) -> None:
    with pytest.raises(mod.LockfileSyncError, match=r"requirements\.in:1 .*'fastapi>>0\.115'"):
        _violations(tmp_path, "fastapi>>0.115\n", _lock("fastapi==0.136.3"))


@pytest.mark.parametrize(
    "option",
    ["-r other.in", "-rother.in", "--requirement=other.in", "-c constraints.txt", "-e ./pkg"],
)
def test_option_that_hides_requirements_fails_loud(tmp_path: Path, option: str) -> None:
    with pytest.raises(mod.LockfileSyncError, match="esconde requisitos"):
        _violations(tmp_path, f"{option}\n", _lock("fastapi==0.136.3"))


def test_marker_on_python_full_version_fails_loud(tmp_path: Path) -> None:
    in_text = "tomli>=2.0; python_full_version < '3.12.4'\n"
    with pytest.raises(mod.LockfileSyncError, match="python_full_version"):
        _violations(tmp_path, in_text, _lock("tomli==2.2.1"))


def test_lock_without_pip_compile_header_fails_loud(tmp_path: Path) -> None:
    with pytest.raises(mod.LockfileSyncError, match="Python X.Y"):
        _violations(tmp_path, "fastapi>=0.115\n", "fastapi==0.136.3\n")


def test_main_reports_and_fails_on_violation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    in_file, lock_file = tmp_path / "requirements.in", tmp_path / "requirements.lock"
    in_file.write_text("greenlet>=3.5.6\n", encoding="utf-8")
    lock_file.write_text(_lock("greenlet==3.5.1"), encoding="utf-8")
    monkeypatch.setattr(mod, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(mod, "IN_FILES", (in_file,))
    monkeypatch.setattr(mod, "LOCK_FILE", lock_file)
    assert mod.main() == 1
    out = capsys.readouterr().out
    assert "requirements.in:1  greenlet>=3.5.6  → lock pina 3.5.1" in out
    assert "Tarefa 1" in out


def test_repo_lock_passes_and_one_raised_floor_fails(tmp_path: Path) -> None:
    """Não-inércia sobre os arquivos reais: o lock da árvore passa; um piso acima dele reprova."""
    in_files = tuple(path.relative_to(mod.REPO_ROOT) for path in mod.IN_FILES)
    assert mod.lockfile_violations(mod.IN_FILES, mod.LOCK_FILE, mod.REPO_ROOT) == []
    for relative in (*in_files, mod.LOCK_FILE.relative_to(mod.REPO_ROOT)):
        (tmp_path / relative).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / relative).write_text((mod.REPO_ROOT / relative).read_text(encoding="utf-8"))
    pinned = mod.read_lock_pins(mod.LOCK_FILE.read_text(encoding="utf-8"))["greenlet"]
    backend_in = tmp_path / "backend" / "requirements.in"
    backend_in.write_text(backend_in.read_text() + f"greenlet>{pinned}\n", encoding="utf-8")
    found = mod.lockfile_violations(
        tuple(tmp_path / p for p in in_files), tmp_path / "requirements.lock", tmp_path
    )
    assert found == [
        f"backend/requirements.in:{len(backend_in.read_text().splitlines())}  greenlet>{pinned}  → lock pina {pinned}"
    ]


def _reqs(*lines: str) -> list:
    from packaging.requirements import Requirement

    return [Requirement(line) for line in lines]


def test_otel_family_aligned_per_track_passes() -> None:
    declared = _reqs(
        "opentelemetry-api>=1.45.1",
        "opentelemetry-sdk>=1.45.1",
        "opentelemetry-instrumentation-fastapi>=0.66b1",
        "opentelemetry-instrumentation-celery>=0.66b1",
    )
    assert mod.otel_floor_violations(declared) == []


def test_otel_member_alone_with_new_floor_fails() -> None:
    declared = _reqs(
        "opentelemetry-instrumentation-fastapi>=0.66b0",
        "opentelemetry-instrumentation-celery>=0.65b0",
        "opentelemetry-api>=1.45.1",
    )
    violations = mod.otel_floor_violations(declared)
    assert len(violations) == 1 and "0.Xb0" in violations[0]


def test_otel_member_without_single_floor_fails() -> None:
    violations = mod.otel_floor_violations(
        _reqs("opentelemetry-sdk<2", "opentelemetry-api>=1.45.1")
    )
    assert violations == ["opentelemetry-sdk: esperado um único piso `>=`"]


@pytest.mark.parametrize(("floor", "track"), [("0.66b1", "0.Xb0"), ("1.45.1", "1.x")])
def test_otel_track_from_floor(floor: str, track: str) -> None:
    assert mod.otel_track(floor) == track


def test_repo_otel_family_aligned_and_one_raised_member_fails() -> None:
    backend_in = mod.REPO_ROOT / "backend" / "requirements.in"
    declared = [d.requirement for d in mod.read_declared(backend_in, mod.REPO_ROOT)]
    assert mod.otel_floor_violations(declared) == []
    floors = mod.otel_floors(declared)
    member = next(n for n, f in floors.items() if f and mod.otel_track(f) == "0.Xb0")
    raised = [r for r in declared if r.name.lower() != member] + _reqs(f"{member}>=0.99b0")
    assert mod.otel_floor_violations(raised), f"subir só {member} devia reprovar"
