"""Constantes de categorização de ADRs (inlinadas de dev/build_adr_toc.py — F2.F deleta o script)."""

# Módulo dedicado a dados puros — sem imports, sem lógica. Mantém build_doc_index.py
# <500 linhas (guideline CLAUDE.md). Substituível por loader YAML sem mexer call-sites.

from __future__ import annotations

# Tupla (nome_categoria, keywords_no_título, ranges_numéricos). Primeiro match
# ganha. Ordem da lista = ordem de seções no índice final ("Outras" no fim).
CATEGORIES_LEGACY: list[tuple[str, list[str], list[range]]] = [
    ("Fundação", ["sqlalchemy", "filesystem", "jwt", "vps", "monorepo", "wrap"], [range(1, 14)]),
    (
        "Persistência",
        ["alembic", "postgresql", "sqlite", "docker volume", "fernet"],
        [range(38, 42)],
    ),
    (
        "Pipeline",
        [
            "threading",
            "vault",
            "e0-route",
            "sync session",
            "config_dir",
            "storage_root",
            "cancelamento",
            "content-first",
            "classificação de documentos",
        ],
        [range(14, 20), range(30, 31), range(75, 76), range(79, 80), range(81, 82)],
    ),
    (
        "Config (materialização legada)",
        ["materializar config", "configs editáveis", "fallback seletivo", "import/export"],
        [range(20, 24)],
    ),
    ("LLM", ["litellm", "byok", "instructor", "retry", "e7 full scope"], [range(24, 29)]),
    ("Task Queue", ["celery", "websocket", "redis para queue", "cancel stage"], [range(29, 33)]),
    (
        "Frontend / Design",
        [
            "react components",
            "dashboard completo",
            "media print",
            "recharts",
            "design system antes",
            "shadcn",
            "tailwind",
            "geist fonts",
            "lucide",
            "intl nativo",
            "migração incremental",
        ],
        [range(33, 55)],
    ),
    (
        "Produto",
        ["transaction explorer", "data lineage", "responsivo", "category override"],
        [range(44, 48)],
    ),
    (
        "Produção & Infra (F7)",
        [
            "fernet app-level",
            "billing",
            "traefik",
            "coverage target",
            "rolling restart",
            "jwt 15min",
            "vps cx32",
            "cve scan",
            "fernet dual key",
            "telemetria",
            "subdomínios mathomsai",
        ],
        [range(7, 8), range(40, 42), range(55, 62), range(108, 109)],
    ),
    (
        "Testing",
        [
            "frontend testing em fase",
            "hardening fintech",
            "backend hardening",
            "test infrastructure",
            "msw sync",
            "premium llm e2e",
            "playwright workspace",
        ],
        [range(62, 72)],
    ),
    ("Operations", ["sub-fase 7e", "auth flows completos"], [range(65, 67)]),
    ("UX / Linguagem", ["códigos internos do pipeline"], [range(68, 69)]),
    ("Multi-tenancy (F8)", ["multi-tenancy"], [range(72, 73)]),
    (
        "Goals & Tasks (F8)",
        [
            "goals como entidade",
            "tasks como entidade",
            "cutover cli",
            "pipeline-adapter como contrato",
        ],
        [range(73, 78)],
    ),
    (
        "Design System & Render (F9 / Report Premium)",
        [
            "design tokens unificados",
            "render nativo react",
            "design tokens",
        ],
        [range(76, 79), range(121, 130)],
    ),
    (
        "Pipeline DDD/SOLID + Infra+Domínio (Sprint A6)",
        [
            "pipelineartifact",
            "artifactstore",
            "content-addressed",
            "eliminar materialização",
            "materializationbridge",
            "stagespec",
            "stageconfig",
            "pipelinedomain",
            "decimal",
            "pydantic para domain",
            "renomear scripts",
            "rename completo",
            "report single-active",
            "lgpd",
            "observabilidade de cutover",
            "extract-then-refactor",
            "caminho b",
            "reuse de analyze",
            "a6d commitment",
            "princípios r12-r17",
            "princípios r18-r20",
            "teste manual",
            "e15c",
            "llm stages escrevem",
            "opt-in db artifacts",
            "remoção de materializationbridge",
            "auth portability",
            "stateless-rigoroso",
            "pipeline-as-service",
            "convenções go",
            "skeleton go",
            "domain events",
            "f7f-local",
            "flip do default",
            "livestep",
            "readers db-first",
        ],
        [range(82, 121)],
    ),
    ("Internacionalização (F12)", ["internacionalização"], [range(130, 131)]),
    (
        "Report Premium (F-pós, ondas v1/v2)",
        [
            "scripts/e6_render",
            "ssr standalone",
            "descontinuação completa",
            "report referencia",
            "lifecycle scoping",
            "transferencias_internas",
            "ui de edição",
            "snapshotchangelogbuilder",
            "section_summaries",
            "finalização migração recharts",
            "supervisão cto",
        ],
        [range(122, 130), range(131, 134), range(139, 140), range(144, 145), range(148, 149)],
    ),
    (
        "Sprint A7 — Rules-as-Code & Cutover",
        [
            "configstore",
            "versionamento temporal de séries fiscais",
            "decision aggregate",
            "catalog + override resolver",
            "docs/methodology",
            "rules-as-code",
            "7 categorias canonical",
            "source hierarchy",
            "milhas",
        ],
        [range(134, 138), range(143, 148)],
    ),
    (
        "Decisões metodológicas pós-auditoria (Roadmap v2)",
        [
            "goal if schema v2",
            "goal alocação-alvo schema v2",
            "toggle `imoveis_no_if`",
            "imoveis_no_if",
        ],
        [range(140, 143)],
    ),
    (
        "Sprint A10 — `goals.json` cutover final",
        [
            "rules-as-code consolidation goals.json",
            "risk aggregate workspace-scoped",
            "decision aggregate — extensão de schema",
            "goals.json cutover final via stageconfig",
            "goals.json removido de `_archive/`",
        ],
        [range(177, 182)],
    ),
]

# Overrides por número quando a heurística de keywords/ranges erra. Decisão
# explícita por ADR (inlinado de dev/build_adr_toc.py).
OVERRIDES_LEGACY: dict[int, str] = {
    7: "Produção & Infra (F7)",
    40: "Produção & Infra (F7)",
    41: "Produção & Infra (F7)",
    57: "Produção & Infra (F7)",
    58: "Produção & Infra (F7)",
    60: "Produção & Infra (F7)",
    65: "Operations",
    66: "Operations",
    68: "UX / Linguagem",
    76: "Design System & Render (F9 / Report Premium)",
    77: "Goals & Tasks (F8)",
    78: "Design System & Render (F9 / Report Premium)",
    80: "Pipeline",
    106: "Pipeline DDD/SOLID + Infra+Domínio (Sprint A6)",
    109: "Pipeline DDD/SOLID + Infra+Domínio (Sprint A6)",
    116: "Produção & Infra (F7)",
    138: "Sprint A7 — Rules-as-Code & Cutover",
    139: "Frontend / Design",
    144: "Report Premium (F-pós, ondas v1/v2)",
    148: "Report Premium (F-pós, ondas v1/v2)",
    177: "Sprint A10 — `goals.json` cutover final",
    178: "Sprint A10 — `goals.json` cutover final",
    179: "Sprint A10 — `goals.json` cutover final",
    180: "Sprint A10 — `goals.json` cutover final",
    181: "Sprint A10 — `goals.json` cutover final",
    182: "Outras",
}
