"""Renderers dos context packs compactos para agentes."""

from __future__ import annotations

from typing import Callable

PackLines = list[str]
PackSpec = tuple[str, tuple[str, ...]]

_FOOTER = ("---", "> Regenerar: `python3 dev/build_doc_index.py --inline`")

_PACKS: dict[str, PackSpec] = {
    "CONTEXT_INDEX.md": (
        "CONTEXT_INDEX - leitura minima por intencao",
        (
            "Use este indice antes de abrir a vault inteira. Escolha 1 pack, leia as fontes",
            "indicadas e so depois faca buscas estreitas com `rg`.",
            "",
            "| Intencao | Pack | Fontes curtas sempre uteis |",
            "| --- | --- | --- |",
            "| Engenharia geral | [`CONTEXT_ENGINEERING`](CONTEXT_ENGINEERING.md) | [`SPRINT_CURRENT`](SPRINT_CURRENT.md), [`PLAN_PROGRESS`](PLAN_PROGRESS.md), [`ADR_INDEX`](ADR_INDEX.md) |",
            "| Backend/API/pipeline | [`CONTEXT_BACKEND`](CONTEXT_BACKEND.md) | [`ARCHITECTURE`](../../reference/ARCHITECTURE.md), [`PIPELINE_ARTIFACTS`](../../reference/PIPELINE_ARTIFACTS.md) |",
            "| Frontend/relatorio | [`CONTEXT_FRONTEND`](CONTEXT_FRONTEND.md) | [`PRODUCT`](../../reference/PRODUCT.md), [`COPY_GUIDELINES`](../../reference/COPY_GUIDELINES.md) |",
            "| Produto/dominio financeiro | [`CONTEXT_PRODUCT`](CONTEXT_PRODUCT.md) | [`FORMULAS`](../../reference/FORMULAS.md), [`reference/rules`](../../reference/rules/) |",
            "| Documentacao/vault | [`CONTEXT_DOCS`](CONTEXT_DOCS.md) | [`00-INDEX`](../00-INDEX.md), [`DOC_STATS`](DOC_STATS.md) |",
            "",
            "Regra de economia: evite `rg docs` amplo. Prefira `rg <termo> docs/reference docs/plan`",
            "ou o bucket indicado pelo pack. Consulte `docs/archive/**` apenas para arqueologia.",
            "",
        ),
    ),
    "CONTEXT_ENGINEERING.md": (
        "CONTEXT_ENGINEERING - mudancas gerais",
        (
            "Use para tarefas que cruzam arquitetura, tests, CI, contratos ou varios buckets.",
            "",
            "## Leia primeiro",
            "",
            "- [`SPRINT_CURRENT.md`](SPRINT_CURRENT.md) - lanes ativas e prontas.",
            "- [`PLAN_PROGRESS.md`](PLAN_PROGRESS.md) - planos canonicos abertos e status.",
            "- [`ADR_INDEX.md`](ADR_INDEX.md) - decisoes vigentes por area.",
            "- [`DOC_STATS.md`](DOC_STATS.md) - tamanho da vault antes de buscar.",
            "- [`CLAUDE.md`](../../../CLAUDE.md) - invariantes de agente e protocolo git.",
            "",
            "## Onde procurar",
            "",
            "- Arquitetura tecnica: [`ARCHITECTURE`](../../reference/ARCHITECTURE.md).",
            "- Setup/runbook/testes: [`SETUP`](../../reference/SETUP.md), [`RUNBOOK`](../../reference/RUNBOOK.md), [`TESTING`](../../reference/TESTING.md).",
            "- Pipeline/artifacts: [`PIPELINE_ARTIFACTS`](../../reference/PIPELINE_ARTIFACTS.md).",
            "- Planos grandes: [`docs/plan`](../../plan/).",
            "- Lanes/tracks: [`docs/sprint`](../../sprint/).",
            "",
            "## Invariantes que evitam retrabalho",
            "",
            "- Dinheiro nunca e `float`; siga ADR-090.",
            "- `pipeline/**` nao importa FastAPI/Celery/SQLAlchemy.",
            "- Backend e pipeline devem ser stateless salvo excecoes registradas.",
            "- JSON endpoint novo exige `response_model` e snapshot OpenAPI.",
            "- ArtifactStore e DB-only; testes injetam store explicito.",
            "",
            "## Verificacao base",
            "",
            "- Docs: `python3 dev/build_doc_index.py --check` e `python3 dev/check_doc_markdown_links.py --report`.",
            "- Python touched files: `.venv/bin/ruff check <files>`.",
            "- Suite direcionada: rode o menor pytest que cubra o contrato alterado.",
            "",
        ),
    ),
    "CONTEXT_BACKEND.md": (
        "CONTEXT_BACKEND - API, pipeline e dados",
        (
            "Use para FastAPI, pipeline, DB, migrations, artifacts, auth e jobs.",
            "",
            "## Leia primeiro",
            "",
            "- [`ARCHITECTURE`](../../reference/ARCHITECTURE.md) - stack, camadas e glossary.",
            "- [`PIPELINE_ARTIFACTS`](../../reference/PIPELINE_ARTIFACTS.md) - contrato de artefatos.",
            "- [`RUNBOOK`](../../reference/RUNBOOK.md) - operacao e incidentes.",
            "- [`STATELESS_AUDIT`](../../reference/STATELESS_AUDIT.md) - globais permitidos.",
            "- [`ADR_INDEX`](ADR_INDEX.md) filtrando mentalmente por API, pipeline, auth, DB e LLMOps.",
            "",
            "## Hot paths",
            "",
            "- `backend/app/api/` - routers e DTO boundaries.",
            "- `backend/app/application/` - use cases.",
            "- `backend/app/repositories/` e `backend/alembic/` - persistencia/migrations.",
            "- `backend/app/services/` - adapters e integracoes.",
            "- `pipeline/domain/services/` - regras puras de dominio.",
            "- `config/schemas/` - contratos JSON.",
            "",
            "## Checks comuns",
            "",
            "- Backend: `pytest backend/tests -q`.",
            "- Pipeline: `pytest tests -q` ou teste unitario/golden direcionado.",
            "- Boundary: `python3 dev/check_pipeline_boundaries.py`.",
            "- Frontmatter/docs se mexer em ADR/plano: `python3 dev/validate_frontmatter.py`.",
            "",
        ),
    ),
    "CONTEXT_FRONTEND.md": (
        "CONTEXT_FRONTEND - app e relatorio",
        (
            "Use para Next.js, componentes do relatorio, UX, design tokens, copy e testes UI.",
            "",
            "## Leia primeiro",
            "",
            "- [`PRODUCT`](../../reference/PRODUCT.md) - intencao do produto.",
            "- [`COPY_GUIDELINES`](../../reference/COPY_GUIDELINES.md) - tom e restricoes publicas.",
            "- [`REPORT_PREMIUM`](../../plan/REPORT_PREMIUM/_README.md) - plano canonico do relatorio.",
            "- [`MOBILE_SPEC`](../../plan/REPORT_PREMIUM/MOBILE_SPEC.md) - comportamento responsivo.",
            "- [`A11Y_CHECKLIST`](../../plan/REPORT_PREMIUM/A11Y_CHECKLIST.md) - gate acessibilidade.",
            "",
            "## Hot paths",
            "",
            "- `frontend/src/app/` - rotas Next.",
            "- `frontend/src/components/report/` - relatorio premium.",
            "- `frontend/src/generated/` - tipos/codegen; nao editar manualmente.",
            "- `frontend/tests/` - Vitest e Playwright.",
            "- `design-tokens/` e `frontend/src/styles/` - tokens e CSS base.",
            "",
            "## Checks comuns",
            "",
            "- Unit: `cd frontend && npm test -- --run`.",
            "- E2E critico: `cd frontend && npm run test:e2e`.",
            "- Codegen quando layout muda: `python3 dev/codegen_report_layout.py --check`.",
            "- Visual/a11y: seguir checklist do plano antes de declarar pronto.",
            "",
        ),
    ),
    "CONTEXT_PRODUCT.md": (
        "CONTEXT_PRODUCT - dominio financeiro",
        (
            "Use para regras de planejamento, relatorio ao cliente, metodologia e copy de produto.",
            "",
            "## Leia primeiro",
            "",
            "- [`PRODUCT`](../../reference/PRODUCT.md) - promessa e escopo do produto.",
            "- [`FORMULAS`](../../reference/FORMULAS.md) - formulas e conceitos calculados.",
            "- [`reference/rules`](../../reference/rules/) - regras de dominio materializadas.",
            "- [`PLAN_PROGRESS`](PLAN_PROGRESS.md) - iniciativas abertas por plano.",
            "- [`ADR_INDEX`](ADR_INDEX.md) - decisoes de produto e dominio.",
            "",
            "## Guardrails",
            "",
            "- Nao invente regra financeira: consulte `config/`, `reference/rules/` e ADRs.",
            "- Dados sensiveis nunca entram em docs, fixtures, logs ou exemplos.",
            "- Methodology = code: regra universal vive perto do enforcer + ADR.",
            "- Copy publica nao atribui marcas/metodologias de terceiros.",
            "- Mudanca em dinheiro, reserva, divida, IF ou alocacao pede `financial-planner`.",
            "",
            "## Busca economica",
            "",
            "- Comece por `rg <conceito> docs/reference docs/plan docs/adr`.",
            "- Se a pergunta for sobre sprint, use `docs/sprint/<X>/` em vez de vault inteira.",
            "- Abra `docs/archive/**` so para entender decisao historica ou plano substituido.",
            "",
        ),
    ),
    "CONTEXT_DOCS.md": (
        "CONTEXT_DOCS - vault e economia de tokens",
        (
            "Use para editar docs, criar plano/ADR/lane/track ou investigar a organizacao da vault.",
            "",
            "## Leia primeiro",
            "",
            "- [`00-INDEX`](../00-INDEX.md) - entrada editorial da vault.",
            "- [`DOC_STATS`](DOC_STATS.md) - inventario compacto.",
            "- [`SPRINT_CURRENT`](SPRINT_CURRENT.md) - trabalho ativo.",
            "- [`PLAN_PROGRESS`](PLAN_PROGRESS.md) - planos canonicos e lanes ligadas.",
            "- [`CHANGELOG_RECENT`](CHANGELOG_RECENT.md) - entregas recentes.",
            "",
            "## Onde escrever",
            "",
            "- Plano multi-fase: `docs/plan/<TOPIC>/_README.md`.",
            "- Lane/track operacional: `docs/sprint/<SPRINT>/lanes/` ou `docs/sprint/<SPRINT>/tracks/`.",
            "- Decisao arquitetural/produto: `docs/adr/NNN-slug.md`.",
            "- Referencia estavel: `docs/reference/`.",
            "- Historico substituido: `docs/archive/` com nota no indice do archive.",
            "",
            "## Gates de docs",
            "",
            "- `python3 dev/validate_frontmatter.py`.",
            "- `python3 dev/check_doc_filename_id.py`.",
            "- `python3 dev/check_doc_links.py`.",
            "- `python3 dev/check_doc_markdown_links.py --report --limit 0`.",
            "- `python3 dev/build_doc_index.py --check`.",
            "- `python3 dev/benchmark_doc_token_cost.py --check`.",
            "",
            "## Politica de token",
            "",
            "- Leia MOCs e packs antes de abrir documentos longos.",
            "- Busque por bucket; nao faca varredura ampla em `docs/archive/**`.",
            "- Links quebrados em docs ativos sao bloqueantes; archive e arqueologia.",
            "",
        ),
    ),
}


def _render_pack(header_fn: Callable[[str], PackLines], spec: PackSpec) -> PackLines:
    title, body = spec
    return [*header_fn(title), *body, *_FOOTER]


def render_context_packs(header_fn: Callable[[str], PackLines]) -> dict[str, PackLines]:
    """Retorna context packs gerados, curtos e linkados para fontes canonicas."""
    return {name: _render_pack(header_fn, spec) for name, spec in _PACKS.items()}
