#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Pre-commit hook: requirements.lock em sincronia com os *.in (ADR-254)."""

# Falha se um pacote direto declarado em requirements.in/backend/requirements.in
# está ausente do lock combinado requirements.lock, ou se o pin do lock não
# satisfaz o especificador do .in (piso acima do lock, teto abaixo dele). NÃO
# regenera o lock — isso exige container linux/amd64 (runbook
# docs/reference/runbooks/python_dependencies.md); só detecta drift. Roda com
# pass_filenames: false (conjunto fixo).
#
# Até 2026-10-09 só conferia presença: PR do Dependabot subia o piso no .in sem
# regenerar o lock e passava verde — em 2026-10-08 a main violava 5 pisos (#2046).
#
# Família opentelemetry-*: os pisos `>=` de cada trilha (core 1.x, contrib
# 0.Xb0) têm que ser iguais. A família é acoplada por `==` (sdk 1.Y ⇒
# api==1.Y; instrumentation 0.Xb ⇒ semantic-conventions==0.Xb), então um membro
# sozinho com piso novo pede uma combinação que o lock não tem — e o Dependabot
# propõe um membro por PR (#2101/#2102 partiram a família em 2026-10-09).

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    from packaging.markers import default_environment
    from packaging.requirements import InvalidRequirement, Requirement
    from packaging.utils import canonicalize_name
    from packaging.version import Version
except ImportError as exc:  # fail-closed: sem packaging o gate não mede nada
    sys.exit(f"[lockfile-sync] requer o pacote `packaging` (pip install packaging): {exc}")

REPO_ROOT = Path(__file__).resolve().parent.parent
IN_FILES = (REPO_ROOT / "requirements.in", REPO_ROOT / "backend" / "requirements.in")
LOCK_FILE = REPO_ROOT / "requirements.lock"
RUNBOOK_HINT = "regenere o lock (docs/reference/runbooks/python_dependencies.md Tarefa 1)"
OTEL_HINT = (
    "suba a família inteira junto "
    "(runbook python_dependencies.md §Uma entrada pip e a família opentelemetry)"
)
_OTEL_PREFIX = "opentelemetry-"

_INLINE_COMMENT = re.compile(r"(^|\s+)#.*$")  # mesma regra do parser de requirements do pip
# Opções que trazem requisitos de outro arquivo: o gate não os veria — falha em vez de pular.
_NESTED_OPTION = re.compile(r"^(-[rce]|--requirement|--constraint|--editable)")
_LOCK_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^\]]*\])?==([^\s;\\]+)")
_LOCK_PYTHON = re.compile(r"autogenerated by pip-compile with Python (\d+\.\d+)")
# Alvo do lock: container linux/amd64 (ADR-254); a versão do Python sai do header.
_LOCK_PLATFORM = {
    "os_name": "posix",
    "sys_platform": "linux",
    "platform_system": "Linux",
    "platform_machine": "x86_64",
    "implementation_name": "cpython",
    "platform_python_implementation": "CPython",
}


class LockfileSyncError(ValueError):
    """Entrada que o gate não consegue medir — falha em vez de passar calado."""


@dataclass(frozen=True)
class DeclaredRequirement:
    source: str
    text: str
    requirement: Requirement


def _parse_in_line(source: str, text: str) -> DeclaredRequirement:
    try:
        requirement = Requirement(text)
    except InvalidRequirement as exc:
        raise LockfileSyncError(f"{source} requisito ilegível {text!r}: {exc}") from exc
    # O header do pip-compile só dá X.Y; avaliar contra um patch inventado seria chute.
    if requirement.marker is not None and "python_full_version" in str(requirement.marker):
        raise LockfileSyncError(
            f"{source} marcador com python_full_version não é medível: {text!r}"
        )
    return DeclaredRequirement(source, text, requirement)


def _is_requirement_line(source: str, text: str) -> bool:
    if _NESTED_OPTION.match(text):
        raise LockfileSyncError(f"{source} opção que esconde requisitos do gate: {text!r}")
    return bool(text) and not text.startswith("-")


def read_declared(path: Path, root: Path) -> list[DeclaredRequirement]:
    """Requisitos de um .in, com `arquivo:linha` relativo a `root`."""
    label = path.relative_to(root).as_posix()
    declared: list[DeclaredRequirement] = []
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        text = _INLINE_COMMENT.sub("", raw).strip()
        if _is_requirement_line(f"{label}:{number}", text):
            declared.append(_parse_in_line(f"{label}:{number}", text))
    return declared


def read_lock_pins(lock_text: str) -> dict[str, str]:
    """Nome canônico (PEP 503) → versão pinada com `==`."""
    pins: dict[str, str] = {}
    for raw in lock_text.splitlines():
        match = _LOCK_PIN.match(raw)
        if match:
            pins[canonicalize_name(match.group(1))] = match.group(2)
    return pins


def lock_target_environment(lock_text: str) -> dict[str, str]:
    """Ambiente de marcadores do alvo do lock (Python do header do pip-compile)."""
    match = _LOCK_PYTHON.search(lock_text)
    if match is None:
        raise LockfileSyncError(
            "header do pip-compile ausente no lock: esperado "
            "'autogenerated by pip-compile with Python X.Y'"
        )
    return {**default_environment(), **_LOCK_PLATFORM, "python_version": match.group(1)}


def _violation(
    declared: DeclaredRequirement, pins: dict[str, str], env: dict[str, str]
) -> str | None:
    requirement = declared.requirement
    if requirement.marker is not None and not requirement.marker.evaluate(env):
        return None
    pinned = pins.get(canonicalize_name(requirement.name))
    if pinned is None:
        return f"{declared.source}  {declared.text}  → ausente do lock"
    # prereleases=True: o pin já existe; a pergunta é só se ele cabe no intervalo.
    if requirement.specifier.contains(pinned, prereleases=True):
        return None
    return f"{declared.source}  {declared.text}  → lock pina {pinned}"


def lockfile_violations(in_files: tuple[Path, ...], lock_file: Path, root: Path) -> list[str]:
    """Uma linha por requisito dos .in que o lock não satisfaz."""
    lock_text = lock_file.read_text(encoding="utf-8")
    pins, env = read_lock_pins(lock_text), lock_target_environment(lock_text)
    declared = [item for path in in_files for item in read_declared(path, root)]
    return [found for item in declared if (found := _violation(item, pins, env))]


def _floor(requirement: Requirement) -> str | None:
    floors = [spec.version for spec in requirement.specifier if spec.operator == ">="]
    return floors[0] if len(floors) == 1 else None


def otel_floors(declared: list[Requirement]) -> dict[str, str | None]:
    """Piso `>=` de cada dep opentelemetry-* (None quando não há exatamente um)."""
    return {
        canonicalize_name(req.name): _floor(req)
        for req in declared
        if canonicalize_name(req.name).startswith(_OTEL_PREFIX)
    }


def otel_track(floor: str) -> str:
    return "0.Xb0" if Version(floor).major == 0 else "1.x"


def otel_floor_violations(declared: list[Requirement]) -> list[str]:
    """Uma linha por trilha otel com pisos distintos, ou membro sem piso único."""
    floors = otel_floors(declared)
    missing = [f"{name}: esperado um único piso `>=`" for name, f in floors.items() if f is None]
    tracks: dict[str, dict[str, str]] = {}
    for name, floor in floors.items():
        if floor is not None:
            tracks.setdefault(otel_track(floor), {})[name] = floor
    return missing + [
        f"opentelemetry-* {track}: pisos distintos {by_name}"
        for track, by_name in sorted(tracks.items())
        if len({Version(v) for v in by_name.values()}) > 1
    ]


def _report(header: str, violations: list[str]) -> int:
    if not violations:
        return 0
    print(f"[lockfile-sync] {header}:")
    print("\n".join(f"  {line}" for line in violations))
    return 1


def _missing_inputs() -> list[str]:
    paths = (*IN_FILES, LOCK_FILE)
    return [
        f"[lockfile-sync] esperado {path} não encontrado." for path in paths if not path.exists()
    ]


def main() -> int:
    missing = _missing_inputs()
    if missing:
        print("\n".join(missing))
        return 1
    try:
        violations = lockfile_violations(IN_FILES, LOCK_FILE, REPO_ROOT)
        declared = [d.requirement for f in IN_FILES for d in read_declared(f, REPO_ROOT)]
    except LockfileSyncError as exc:
        print(f"[lockfile-sync] {exc}")
        return 1
    lock_rc = _report(f"{LOCK_FILE.name} não satisfaz os *.in → {RUNBOOK_HINT}", violations)
    family_rc = _report(
        f"família opentelemetry partida → {OTEL_HINT}", otel_floor_violations(declared)
    )
    return lock_rc | family_rc


if __name__ == "__main__":
    sys.exit(main())
