#!/usr/bin/env python3
"""Gera o registry de stages Go a partir de ``pipeline.stage_spec`` (F1 GO_SHELL).

Decisão 2 do track f1-go-service: o shell Go valida 404 (single) e 400
(sequence, ANTES de qualquer subprocess) e decide ``skip_llm`` localmente —
uma única fonte codegen, com teste de sync que falha em drift (padrão
``codegen_report_layout``, ADR-076). Resolução legacy→descritivo espelha
``resolve_stage_name`` (ADR-093).

Uso: python3 dev/codegen_stage_registry_go.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

DST = REPO_ROOT / "services" / "pipeline-service-go" / "internal" / "stages" / "registry_gen.go"

_HEADER = """// Code generated by dev/codegen_stage_registry_go.py; DO NOT EDIT.
// Fonte: pipeline/stage_spec.py (STAGE_REGISTRY + STAGE_RENAME_MAP, ADR-093).
// Sync garantido por tests/test_go_codegen_sync.py.

package stages

import "sort"
"""


def _render_maps() -> tuple[str, str, str]:
    from pipeline.stage_spec import STAGE_REGISTRY, STAGE_RENAME_MAP

    valid = "\n".join(f'\t"{name}": true,' for name in sorted(STAGE_REGISTRY))
    legacy = "\n".join(f'\t"{k}": "{v}",' for k, v in sorted(STAGE_RENAME_MAP.items()) if k != v)
    is_llm = "\n".join(
        f'\t"{name}": {str(spec.is_llm).lower()},' for name, spec in sorted(STAGE_REGISTRY.items())
    )
    return valid, legacy, is_llm


_BODY_TEMPLATE = """{header}
// ValidStages: nomes descritivos canônicos (chaves de STAGE_REGISTRY).
var ValidStages = map[string]bool{{
{valid}
}}

// LegacyToDescriptive: aliases legados ("E3") → descritivo (STAGE_RENAME_MAP).
var LegacyToDescriptive = map[string]string{{
{legacy}
}}

// IsLLM: stage descritivo → envolve LLM (governa skip_llm).
var IsLLM = map[string]bool{{
{is_llm}
}}

// Resolve espelha resolve_stage_name (ADR-093): legacy → descritivo;
// desconhecidos passam through.
func Resolve(name string) string {{
\tif d, ok := LegacyToDescriptive[name]; ok {{
\t\treturn d
\t}}
\treturn name
}}

// IsValid aceita nome legacy ou descritivo.
func IsValid(name string) bool {{
\treturn ValidStages[Resolve(name)]
}}

// IsLLMStage aceita nome legacy ou descritivo.
func IsLLMStage(name string) bool {{
\treturn IsLLM[Resolve(name)]
}}

// SortedValidStages: lista ordenada p/ mensagens de erro (paridade com
// f"(valid: {{sorted(STAGE_REGISTRY)}})" do Python).
func SortedValidStages() []string {{
\tout := make([]string, 0, len(ValidStages))
\tfor name := range ValidStages {{
\t\tout = append(out, name)
\t}}
\tsort.Strings(out)
\treturn out
}}
"""


def render() -> str:
    valid, legacy, is_llm = _render_maps()
    return _BODY_TEMPLATE.format(header=_HEADER, valid=valid, legacy=legacy, is_llm=is_llm)


def _gofmt(src: str) -> str:
    import shutil
    import subprocess

    if not shutil.which("gofmt"):
        raise SystemExit("✗ gofmt não encontrado no PATH — necessário para canonizar o gerado")
    proc = subprocess.run(["gofmt", "-s"], input=src, capture_output=True, text=True, check=True)
    return proc.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = _gofmt(render())
    if args.check:
        if not DST.exists() or DST.read_text(encoding="utf-8") != rendered:
            print(f"✗ {DST.name} dessincronizado — rode python3 dev/codegen_stage_registry_go.py")
            return 1
        print(f"✓ {DST.name} em sync")
        return 0
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(rendered, encoding="utf-8")
    print(f"✓ escrito {DST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
