// Code generated by dev/codegen_stage_registry_go.py; DO NOT EDIT.
// Fonte: pipeline/stage_spec.py (STAGE_REGISTRY + STAGE_RENAME_MAP, ADR-093).
// Sync garantido por tests/test_go_codegen_sync.py.

package stages

import "sort"

// ValidStages: nomes descritivos canônicos (chaves de STAGE_REGISTRY).
var ValidStages = map[string]bool{
	"analyze_finances":          true,
	"categorize_transactions":   true,
	"consolidate_baseline":      true,
	"extract_baseline":          true,
	"extract_comprovantes_bens": true,
	"extract_informe_aluguel":   true,
	"extract_informes_anuais":   true,
	"extract_invoices":          true,
	"extract_irpf_full":         true,
	"extract_members":           true,
	"extract_statements":        true,
	"extract_with_llm":          true,
	"generate_narratives":       true,
	"reconcile_transactions":    true,
	"review_finances_holistic":  true,
	"route_documents":           true,
	"unlock_documents":          true,
	"validate_cross":            true,
}

// LegacyToDescriptive: aliases legados ("E3") → descritivo (STAGE_RENAME_MAP).
var LegacyToDescriptive = map[string]string{
	"E0-route":           "route_documents",
	"E0-unlock":          "unlock_documents",
	"E1":                 "extract_members",
	"E1.5":               "extract_baseline",
	"E1.5c":              "consolidate_baseline",
	"E1.6":               "extract_irpf_full",
	"E2-comprovante-bem": "extract_comprovantes_bens",
	"E2-extratos":        "extract_statements",
	"E2-faturas":         "extract_invoices",
	"E2-informe-aluguel": "extract_informe_aluguel",
	"E2-informe-anual":   "extract_informes_anuais",
	"E2-llm":             "extract_with_llm",
	"E3":                 "reconcile_transactions",
	"E4":                 "categorize_transactions",
	"E5":                 "analyze_finances",
	"E5.N":               "generate_narratives",
	"E6-parecer":         "review_finances_holistic",
	"E7-crossval":        "validate_cross",
}

// IsLLM: stage descritivo → envolve LLM (governa skip_llm).
var IsLLM = map[string]bool{
	"analyze_finances":          false,
	"categorize_transactions":   false,
	"consolidate_baseline":      false,
	"extract_baseline":          true,
	"extract_comprovantes_bens": true,
	"extract_informe_aluguel":   true,
	"extract_informes_anuais":   true,
	"extract_invoices":          false,
	"extract_irpf_full":         true,
	"extract_members":           true,
	"extract_statements":        false,
	"extract_with_llm":          true,
	"generate_narratives":       false,
	"reconcile_transactions":    false,
	"review_finances_holistic":  true,
	"route_documents":           false,
	"unlock_documents":          false,
	"validate_cross":            false,
}

// Resolve espelha resolve_stage_name (ADR-093): legacy → descritivo;
// desconhecidos passam through.
func Resolve(name string) string {
	if d, ok := LegacyToDescriptive[name]; ok {
		return d
	}
	return name
}

// IsValid aceita nome legacy ou descritivo.
func IsValid(name string) bool {
	return ValidStages[Resolve(name)]
}

// IsLLMStage aceita nome legacy ou descritivo.
func IsLLMStage(name string) bool {
	return IsLLM[Resolve(name)]
}

// SortedValidStages: lista ordenada p/ mensagens de erro (paridade com
// f"(valid: {sorted(STAGE_REGISTRY)})" do Python).
func SortedValidStages() []string {
	out := make([]string, 0, len(ValidStages))
	for name := range ValidStages {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}
