"""phase3_config_models_family_category_blobs

Revision ID: da5a6af13e3e
Revises: 0412b148b9d6
Create Date: 2026-04-14 07:19:46.662172
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "da5a6af13e3e"
down_revision: Union[str, None] = "0412b148b9d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category_type", sa.String(length=10), nullable=False),
        sa.Column("monthly_cap", sa.Float(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "family_members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=100), nullable=False),
        sa.Column("cpf_encrypted", sa.Text(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("family_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_family_members_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "institution_configs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("institution_configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_institution_configs_workspace_id"), ["workspace_id"], unique=True
        )

    op.create_table(
        "pipeline_configs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pipeline_configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pipeline_configs_workspace_id"), ["workspace_id"], unique=True
        )

    op.create_table(
        "report_layouts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("report_layouts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_report_layouts_workspace_id"), ["workspace_id"], unique=True
        )

    op.create_table(
        "bank_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("institution_code", sa.String(length=50), nullable=False),
        sa.Column("account_type", sa.String(length=100), nullable=False),
        sa.Column("agency", sa.String(length=20), nullable=True),
        sa.Column("account_number", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(["member_id"], ["family_members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bank_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bank_accounts_member_id"), ["member_id"], unique=False)

    op.create_table(
        "category_keywords",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("keyword", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("category_keywords", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_category_keywords_category_id"), ["category_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category_keywords", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_keywords_category_id"))

    op.drop_table("category_keywords")
    with op.batch_alter_table("bank_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bank_accounts_member_id"))

    op.drop_table("bank_accounts")
    with op.batch_alter_table("report_layouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_layouts_workspace_id"))

    op.drop_table("report_layouts")
    with op.batch_alter_table("pipeline_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pipeline_configs_workspace_id"))

    op.drop_table("pipeline_configs")
    with op.batch_alter_table("institution_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_institution_configs_workspace_id"))

    op.drop_table("institution_configs")
    with op.batch_alter_table("family_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_family_members_workspace_id"))

    op.drop_table("family_members")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_workspace_id"))

    op.drop_table("categories")
    # ### end Alembic commands ###
