// Package contracts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package contracts

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// RunStartRequest Input to POST /api/v1/pipeline/runs — run a sequence of stages.
type RunStartRequest struct {
	// BaseRunFallbackStages Stages upstream lidos do run base (ADR-291/ADR-303)
	BaseRunFallbackStages *[]string `json:"base_run_fallback_stages,omitempty"`

	// BaseRunId Run base para fallback run-pinado em from_stage (ADR-291/ADR-303)
	BaseRunId           *string   `json:"base_run_id,omitempty"`
	ConfigDir           *string   `json:"config_dir,omitempty"`
	Incremental         *bool     `json:"incremental,omitempty"`
	IncrementalDocPaths *[]string `json:"incremental_doc_paths,omitempty"`
	RunId               string    `json:"run_id"`
	SkipLlm             *bool     `json:"skip_llm,omitempty"`
	Stages              []string  `json:"stages"`
	StopOnError         *bool     `json:"stop_on_error,omitempty"`
	WorkspaceId         string    `json:"workspace_id"`
	WorkspaceRoot       string    `json:"workspace_root"`
}

// RunSummaryResponse Aggregated result of a multi-stage run.
type RunSummaryResponse struct {
	FailedStage *string                `json:"failed_stage,omitempty"`
	FinishedAt  string                 `json:"finished_at"`
	RunId       string                 `json:"run_id"`
	Stages      []StageExecuteResponse `json:"stages"`
	StartedAt   string                 `json:"started_at"`
	Success     bool                   `json:"success"`
	WorkspaceId string                 `json:"workspace_id"`
}

// ServiceHealthResponse defines model for ServiceHealthResponse.
type ServiceHealthResponse struct {
	Service *string `json:"service,omitempty"`
	Status  *string `json:"status,omitempty"`
	Version string  `json:"version"`
}

// StageExecuteRequest Input to POST /api/v1/pipeline/stages/{stage}/execute.
//
// Backend owns the workspace root on disk and passes it by path — the
// pipeline-service runs the stage in-process using `pipeline.orchestrator`.
// Artifacts are written to/read from that root by the stage runners.
type StageExecuteRequest struct {
	// BaseRunFallbackStages Stages upstream lidos do run base (ADR-291/ADR-303)
	BaseRunFallbackStages *[]string `json:"base_run_fallback_stages,omitempty"`

	// BaseRunId Run base para fallback run-pinado em from_stage (ADR-291/ADR-303)
	BaseRunId           *string   `json:"base_run_id,omitempty"`
	ConfigDir           *string   `json:"config_dir,omitempty"`
	Incremental         *bool     `json:"incremental,omitempty"`
	IncrementalDocPaths *[]string `json:"incremental_doc_paths,omitempty"`

	// RunId Backend-issued PipelineRun UUID
	RunId string `json:"run_id"`

	// SkipLlm Run sem LLM: suprime chamada LLM condicional dentro do stage (classificação E0, section summaries) — ADR-355. O filtro de stages `is_llm` é do chamador; aqui o stage já foi escolhido. Default `false` (≠ do `RunStartRequest`, que assume run determinístico) preserva o comportamento de chamador que não envia o campo.
	SkipLlm     *bool  `json:"skip_llm,omitempty"`
	WorkspaceId string `json:"workspace_id"`

	// WorkspaceRoot Absolute path to tenant root
	WorkspaceRoot string `json:"workspace_root"`
}

// StageExecuteResponse Result of a single stage execution.
type StageExecuteResponse struct {
	Attempts   *int                    `json:"attempts,omitempty"`
	Detail     *map[string]interface{} `json:"detail,omitempty"`
	DurationMs *float32                `json:"duration_ms,omitempty"`
	Error      *string                 `json:"error,omitempty"`
	Stage      string                  `json:"stage"`
	Success    bool                    `json:"success"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// StartRunApiV1PipelineRunsPostJSONRequestBody defines body for StartRunApiV1PipelineRunsPost for application/json ContentType.
type StartRunApiV1PipelineRunsPostJSONRequestBody = RunStartRequest

// ExecuteStageApiV1PipelineStagesStageExecutePostJSONRequestBody defines body for ExecuteStageApiV1PipelineStagesStageExecutePost for application/json ContentType.
type ExecuteStageApiV1PipelineStagesStageExecutePostJSONRequestBody = StageExecuteRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Start Run
	// (POST /api/v1/pipeline/runs)
	StartRunApiV1PipelineRunsPost(w http.ResponseWriter, r *http.Request)
	// Execute Stage
	// (POST /api/v1/pipeline/stages/{stage}/execute)
	ExecuteStageApiV1PipelineStagesStageExecutePost(w http.ResponseWriter, r *http.Request, stage string)
	// Health
	// (GET /health)
	HealthHealthGet(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Start Run
// (POST /api/v1/pipeline/runs)
func (_ Unimplemented) StartRunApiV1PipelineRunsPost(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Execute Stage
// (POST /api/v1/pipeline/stages/{stage}/execute)
func (_ Unimplemented) ExecuteStageApiV1PipelineStagesStageExecutePost(w http.ResponseWriter, r *http.Request, stage string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health
// (GET /health)
func (_ Unimplemented) HealthHealthGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// StartRunApiV1PipelineRunsPost operation middleware
func (siw *ServerInterfaceWrapper) StartRunApiV1PipelineRunsPost(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartRunApiV1PipelineRunsPost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExecuteStageApiV1PipelineStagesStageExecutePost operation middleware
func (siw *ServerInterfaceWrapper) ExecuteStageApiV1PipelineStagesStageExecutePost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "stage" -------------
	var stage string

	err = runtime.BindStyledParameterWithOptions("simple", "stage", chi.URLParam(r, "stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteStageApiV1PipelineStagesStageExecutePost(w, r, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthHealthGet operation middleware
func (siw *ServerInterfaceWrapper) HealthHealthGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthHealthGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/pipeline/runs", wrapper.StartRunApiV1PipelineRunsPost)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/pipeline/stages/{stage}/execute", wrapper.ExecuteStageApiV1PipelineStagesStageExecutePost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthHealthGet)
	})

	return r
}
